server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/topico
    username: root
    password: 078065
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # or other options like "create", "validate", "none"
    show-sql: true # Set to true to see SQL statements in logs
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    jwt:
      header-prefix: Bearer-
      secret: mglhG9oMZDQNH7CuaoREXQ==
      expireHours: 24
    oauth2:
      client:
        registration:
          google:
            client-id: 222091560975-km86grjevp3r51iqg25vltccbg1j9pmr.apps.googleusercontent.com
            client-secret: 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

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true

