version: '3.7'
# docker compose -f docker_compose.yml up -d
# docker compose -f docker_compose.yml down -v

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: topico
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  #      - ./src/main/sql/CREATE_DB.sql:/docker-entrypoint-initdb.d/CREATE_DB.sql

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  # topico spring boot application
  topico-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: topico-service
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    volumes:
      - /tmp:/tmp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/topico?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

volumes:
  mysql-data:
