version: '3.7'
# docker compose -f docker_compose.yml up -d
# docker compose -f docker_compose.yml down -v

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: topico
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  # my spring boot app here
  topico-service:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: topico-service
    depends_on:
      - mysql
      - redis
    ports:
        - "8080:8080"
    volumes:
      - /tmp:/tmp

volumes:
  mysql-data: