server:
  port: 8080
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/topico?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

  data:
    redis:
      top-search-key: top-search
      port: ${SPRING_REDIS_PORT:6379}
      host: ${SPRING_REDIS_HOST:127.0.0.1}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # This logs SQL statements to the console
  type-aliases-package: usyd.elec5619.topicoservice.model # Replace with your package that contains model/entity classes
  mapper-locations: classpath:mappers/*.xml # Path to your MyBatis mapper XML files, adjust if needed

logging:
  level:
    org:
      springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


jwt:
  secret: elec5619elec5619elec5619elec5619elec5619elec5619elec5619elec5619elec5619elec5619elec5619elec5619
  # 7 days
  expire-ms: 604800_000

scheduled:
  updateTopSearch: 60_000  # 1 minute
  updateTopCommunities: 60_000 # 1 minute

