package usyd.elec5619.topicoservice.model;

import java.util.Date;

public class Checkin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.user_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.community_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.accumulated_days
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer accumulatedDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Date utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_checkin.id
     *
     * @return the value of t_checkin.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_checkin.id
     *
     * @param id the value for t_checkin.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_checkin.user_id
     *
     * @return the value of t_checkin.user_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_checkin.user_id
     *
     * @param userId the value for t_checkin.user_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_checkin.community_id
     *
     * @return the value of t_checkin.community_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_checkin.community_id
     *
     * @param communityId the value for t_checkin.community_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_checkin.accumulated_days
     *
     * @return the value of t_checkin.accumulated_days
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getAccumulatedDays() {
        return accumulatedDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_checkin.accumulated_days
     *
     * @param accumulatedDays the value for t_checkin.accumulated_days
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setAccumulatedDays(Integer accumulatedDays) {
        this.accumulatedDays = accumulatedDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_checkin.ctime
     *
     * @return the value of t_checkin.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_checkin.ctime
     *
     * @param ctime the value for t_checkin.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_checkin.utime
     *
     * @return the value of t_checkin.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_checkin.utime
     *
     * @param utime the value for t_checkin.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }
}