package usyd.elec5619.topicoservice.model;

import lombok.*;

import java.util.Date;

@Data
public class Checkin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.user_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.community_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.accumulated_days
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer accumulatedDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.ctime
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_checkin.utime
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Date utime;

}