package usyd.elec5619.topicoservice.model;

import java.util.Date;

public class Community {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.name
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.ctime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.utime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Date utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.deleted
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.description
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community.id
     *
     * @return the value of t_community.id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community.id
     *
     * @param id the value for t_community.id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community.name
     *
     * @return the value of t_community.name
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community.name
     *
     * @param name the value for t_community.name
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community.ctime
     *
     * @return the value of t_community.ctime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community.ctime
     *
     * @param ctime the value for t_community.ctime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community.utime
     *
     * @return the value of t_community.utime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community.utime
     *
     * @param utime the value for t_community.utime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community.deleted
     *
     * @return the value of t_community.deleted
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community.deleted
     *
     * @param deleted the value for t_community.deleted
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community.description
     *
     * @return the value of t_community.description
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community.description
     *
     * @param description the value for t_community.description
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}