package usyd.elec5619.topicoservice.model;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.post_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.author_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.reply_to_comment_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer replyToCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.reply_to_user_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer replyToUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.reply_to_name
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private String replyToName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Date utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.deleted
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Byte deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.content
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.id
     *
     * @return the value of t_comment.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.id
     *
     * @param id the value for t_comment.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.post_id
     *
     * @return the value of t_comment.post_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.post_id
     *
     * @param postId the value for t_comment.post_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.author_id
     *
     * @return the value of t_comment.author_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.author_id
     *
     * @param authorId the value for t_comment.author_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.reply_to_comment_id
     *
     * @return the value of t_comment.reply_to_comment_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getReplyToCommentId() {
        return replyToCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.reply_to_comment_id
     *
     * @param replyToCommentId the value for t_comment.reply_to_comment_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setReplyToCommentId(Integer replyToCommentId) {
        this.replyToCommentId = replyToCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.reply_to_user_id
     *
     * @return the value of t_comment.reply_to_user_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getReplyToUserId() {
        return replyToUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.reply_to_user_id
     *
     * @param replyToUserId the value for t_comment.reply_to_user_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setReplyToUserId(Integer replyToUserId) {
        this.replyToUserId = replyToUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.reply_to_name
     *
     * @return the value of t_comment.reply_to_name
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public String getReplyToName() {
        return replyToName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.reply_to_name
     *
     * @param replyToName the value for t_comment.reply_to_name
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setReplyToName(String replyToName) {
        this.replyToName = replyToName == null ? null : replyToName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.ctime
     *
     * @return the value of t_comment.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.ctime
     *
     * @param ctime the value for t_comment.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.utime
     *
     * @return the value of t_comment.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.utime
     *
     * @param utime the value for t_comment.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.deleted
     *
     * @return the value of t_comment.deleted
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.deleted
     *
     * @param deleted the value for t_comment.deleted
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}