package usyd.elec5619.topicoservice.model;

import lombok.Data;

import java.util.Date;

@Data
public class Community {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.name
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.ctime
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.utime
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Date utime;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community.description
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private String description;

}