package usyd.elec5619.topicoservice.model;

import java.util.Date;

public class CommunityTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community_tag.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community_tag.community_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community_tag.tag_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community_tag.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_community_tag.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Date utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community_tag.id
     *
     * @return the value of t_community_tag.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community_tag.id
     *
     * @param id the value for t_community_tag.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community_tag.community_id
     *
     * @return the value of t_community_tag.community_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community_tag.community_id
     *
     * @param communityId the value for t_community_tag.community_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community_tag.tag_id
     *
     * @return the value of t_community_tag.tag_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community_tag.tag_id
     *
     * @param tagId the value for t_community_tag.tag_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community_tag.ctime
     *
     * @return the value of t_community_tag.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community_tag.ctime
     *
     * @param ctime the value for t_community_tag.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_community_tag.utime
     *
     * @return the value of t_community_tag.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_community_tag.utime
     *
     * @param utime the value for t_community_tag.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }
}