package usyd.elec5619.topicoservice.model;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.uuid
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.path
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private String path;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.uuid
     *
     * @return the value of t_image.uuid
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.uuid
     *
     * @param uuid the value for t_image.uuid
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_image.path
     *
     * @return the value of t_image.path
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_image.path
     *
     * @param path the value for t_image.path
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }
}