package usyd.elec5619.topicoservice.model;

import lombok.*;

@Data
public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.uuid
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_image.path
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private String path;

}