package usyd.elec5619.topicoservice.model;

import lombok.*;

import java.util.Date;

@Data
public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.type
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.sender_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.receiver_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.unread
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Byte unread;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.ctime
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.utime
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Date utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.content
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private String content;

}