package usyd.elec5619.topicoservice.model;

import lombok.Data;

import java.util.Date;

@Data
public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.community_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer communityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.author_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.title
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.content
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.spoiler
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Byte spoiler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.ctime
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.utime
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Date utime;

}