package usyd.elec5619.topicoservice.model;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.community_id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.author_id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.title
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.content
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.spoiler
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Byte spoiler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.ctime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.utime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Date utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.deleted
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    private Byte deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.id
     *
     * @return the value of t_post.id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.id
     *
     * @param id the value for t_post.id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.community_id
     *
     * @return the value of t_post.community_id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.community_id
     *
     * @param communityId the value for t_post.community_id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.author_id
     *
     * @return the value of t_post.author_id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.author_id
     *
     * @param authorId the value for t_post.author_id
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.title
     *
     * @return the value of t_post.title
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.title
     *
     * @param title the value for t_post.title
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.content
     *
     * @return the value of t_post.content
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.content
     *
     * @param content the value for t_post.content
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.spoiler
     *
     * @return the value of t_post.spoiler
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Byte getSpoiler() {
        return spoiler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.spoiler
     *
     * @param spoiler the value for t_post.spoiler
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setSpoiler(Byte spoiler) {
        this.spoiler = spoiler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.ctime
     *
     * @return the value of t_post.ctime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.ctime
     *
     * @param ctime the value for t_post.ctime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.utime
     *
     * @return the value of t_post.utime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.utime
     *
     * @param utime the value for t_post.utime
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.deleted
     *
     * @return the value of t_post.deleted
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.deleted
     *
     * @param deleted the value for t_post.deleted
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }
}