package usyd.elec5619.topicoservice.model;

import lombok.*;

@Data
public class PostTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post_tag.id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post_tag.post_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post_tag.tag_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer tagId;

}