package usyd.elec5619.topicoservice.model;

import lombok.*;

import java.util.Date;

@Data
public class UserLikeComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_like_comment.id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_like_comment.user_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_like_comment.author_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_like_comment.comment_id
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_like_comment.like
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Byte like;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_like_comment.ctime
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_like_comment.utime
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    private Date utime;

}