package usyd.elec5619.topicoservice.model;

import java.util.Date;

public class UserCommunityRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_community_role.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_community_role.user_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_community_role.community_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer communityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_community_role.role_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_community_role.level
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_community_role.exp
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Integer exp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_community_role.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_community_role.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    private Date utime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_community_role.id
     *
     * @return the value of t_user_community_role.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_community_role.id
     *
     * @param id the value for t_user_community_role.id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_community_role.user_id
     *
     * @return the value of t_user_community_role.user_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_community_role.user_id
     *
     * @param userId the value for t_user_community_role.user_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_community_role.community_id
     *
     * @return the value of t_user_community_role.community_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_community_role.community_id
     *
     * @param communityId the value for t_user_community_role.community_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_community_role.role_id
     *
     * @return the value of t_user_community_role.role_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_community_role.role_id
     *
     * @param roleId the value for t_user_community_role.role_id
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_community_role.level
     *
     * @return the value of t_user_community_role.level
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_community_role.level
     *
     * @param level the value for t_user_community_role.level
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_community_role.exp
     *
     * @return the value of t_user_community_role.exp
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_community_role.exp
     *
     * @param exp the value for t_user_community_role.exp
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_community_role.ctime
     *
     * @return the value of t_user_community_role.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_community_role.ctime
     *
     * @param ctime the value for t_user_community_role.ctime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_community_role.utime
     *
     * @return the value of t_user_community_role.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public Date getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_community_role.utime
     *
     * @param utime the value for t_user_community_role.utime
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    public void setUtime(Date utime) {
        this.utime = utime;
    }
}