package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.BrowseHistory;
import usyd.elec5619.topicoservice.model.BrowseHistoryExample;

public interface BrowseHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    long countByExample(BrowseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int deleteByExample(BrowseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int insert(BrowseHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int insertSelective(BrowseHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    List<BrowseHistory> selectByExample(BrowseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    BrowseHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByExampleSelective(@Param("row") BrowseHistory row, @Param("example") BrowseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByExample(@Param("row") BrowseHistory row, @Param("example") BrowseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByPrimaryKeySelective(BrowseHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_browse_history
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByPrimaryKey(BrowseHistory row);
}