package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.Checkin;
import usyd.elec5619.topicoservice.model.CheckinExample;

public interface CheckinMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    long countByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int deleteByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int insert(Checkin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int insertSelective(Checkin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    List<Checkin> selectByExample(CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    Checkin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByExampleSelective(@Param("row") Checkin row, @Param("example") CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByExample(@Param("row") Checkin row, @Param("example") CheckinExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByPrimaryKeySelective(Checkin row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_checkin
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByPrimaryKey(Checkin row);
}