package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.CommunityTag;
import usyd.elec5619.topicoservice.model.CommunityTagExample;

public interface CommunityTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    long countByExample(CommunityTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int deleteByExample(CommunityTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int insert(CommunityTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int insertSelective(CommunityTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    List<CommunityTag> selectByExample(CommunityTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    CommunityTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByExampleSelective(@Param("row") CommunityTag row, @Param("example") CommunityTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByExample(@Param("row") CommunityTag row, @Param("example") CommunityTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByPrimaryKeySelective(CommunityTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByPrimaryKey(CommunityTag row);
}