package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.Community;
import usyd.elec5619.topicoservice.model.CommunityExample;

public interface CommunityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    long countByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int deleteByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int insert(Community row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int insertSelective(Community row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    List<Community> selectByExampleWithBLOBs(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    List<Community> selectByExample(CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    Community selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByExampleSelective(@Param("row") Community row, @Param("example") CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") Community row, @Param("example") CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByExample(@Param("row") Community row, @Param("example") CommunityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByPrimaryKeySelective(Community row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Community row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_community
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByPrimaryKey(Community row);
}