package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.Notification;
import usyd.elec5619.topicoservice.model.NotificationExample;

public interface NotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    long countByExample(NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int deleteByExample(NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int insert(Notification row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int insertSelective(Notification row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    List<Notification> selectByExampleWithBLOBs(NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    List<Notification> selectByExample(NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    Notification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByExampleSelective(@Param("row") Notification row, @Param("example") NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByExampleWithBLOBs(@Param("row") Notification row, @Param("example") NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByExample(@Param("row") Notification row, @Param("example") NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByPrimaryKeySelective(Notification row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Notification row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByPrimaryKey(Notification row);
}