package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.PostTag;
import usyd.elec5619.topicoservice.model.PostTagExample;

public interface PostTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    long countByExample(PostTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int deleteByExample(PostTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int insert(PostTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int insertSelective(PostTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    List<PostTag> selectByExample(PostTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    PostTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByExampleSelective(@Param("row") PostTag row, @Param("example") PostTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByExample(@Param("row") PostTag row, @Param("example") PostTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByPrimaryKeySelective(PostTag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post_tag
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByPrimaryKey(PostTag row);
}