package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.Role;
import usyd.elec5619.topicoservice.model.RoleExample;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int insert(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int insertSelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByExampleSelective(@Param("row") Role row, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByExample(@Param("row") Role row, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByPrimaryKeySelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByPrimaryKey(Role row);
}