package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.RolePermission;
import usyd.elec5619.topicoservice.model.RolePermissionExample;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    long countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int insert(RolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int insertSelective(RolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    List<RolePermission> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    RolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByExampleSelective(@Param("row") RolePermission row, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByExample(@Param("row") RolePermission row, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByPrimaryKeySelective(RolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_permission
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByPrimaryKey(RolePermission row);
}