package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.Tag;
import usyd.elec5619.topicoservice.model.TagExample;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    long countByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int deleteByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int insert(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int insertSelective(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    List<Tag> selectByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    Tag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByExampleSelective(@Param("row") Tag row, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByExample(@Param("row") Tag row, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByPrimaryKeySelective(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tag
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByPrimaryKey(Tag row);
}