package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.UserLikeComment;
import usyd.elec5619.topicoservice.model.UserLikeCommentExample;

public interface UserLikeCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    long countByExample(UserLikeCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int deleteByExample(UserLikeCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int insert(UserLikeComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int insertSelective(UserLikeComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    List<UserLikeComment> selectByExample(UserLikeCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    UserLikeComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByExampleSelective(@Param("row") UserLikeComment row, @Param("example") UserLikeCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByExample(@Param("row") UserLikeComment row, @Param("example") UserLikeCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByPrimaryKeySelective(UserLikeComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_comment
     *
     * @mbg.generated Mon Sep 11 03:54:13 AEST 2023
     */
    int updateByPrimaryKey(UserLikeComment row);
}