package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.UserCommunityRole;
import usyd.elec5619.topicoservice.model.UserCommunityRoleExample;

public interface UserCommunityRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    long countByExample(UserCommunityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int deleteByExample(UserCommunityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int insert(UserCommunityRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int insertSelective(UserCommunityRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    List<UserCommunityRole> selectByExample(UserCommunityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    UserCommunityRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByExampleSelective(@Param("row") UserCommunityRole row, @Param("example") UserCommunityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByExample(@Param("row") UserCommunityRole row, @Param("example") UserCommunityRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByPrimaryKeySelective(UserCommunityRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_community_role
     *
     * @mbg.generated Mon Sep 11 03:55:35 AEST 2023
     */
    int updateByPrimaryKey(UserCommunityRole row);
}