package usyd.elec5619.topicoservice.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import usyd.elec5619.topicoservice.model.UserLikePost;
import usyd.elec5619.topicoservice.model.UserLikePostExample;

public interface UserLikePostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    long countByExample(UserLikePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int deleteByExample(UserLikePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int insert(UserLikePost row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int insertSelective(UserLikePost row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    List<UserLikePost> selectByExample(UserLikePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    UserLikePost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByExampleSelective(@Param("row") UserLikePost row, @Param("example") UserLikePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByExample(@Param("row") UserLikePost row, @Param("example") UserLikePostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByPrimaryKeySelective(UserLikePost row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_like_post
     *
     * @mbg.generated Mon Sep 11 03:49:05 AEST 2023
     */
    int updateByPrimaryKey(UserLikePost row);
}